[package]
name = "wsdclient"
version = "0.1.0"
authors = ["Mykola Sakhno <mykola.sakhno@bitfury.com>"]
edition = "2018"

[dependencies]
clap = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = "0.9"
regex = "1"