[package]
name = "wsdclient"
version = "0.1.0"
authors = ["Mykola Sakhno <mykola.sakhno@bitfury.com>"]
edition = "2018"

[dependencies]
# TODO(mkl): use semver for versions
clap = "2.33.0"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "*"
reqwest = "0.9.14"
regex = "1"